name: Deploy to EC2

on:
  push:
    branches: [ main ]  # Or whichever branch you want to trigger deployments

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Choose your Node version
        
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/GameConnect
            git pull
            cd server
            npm ci
            npx tsc
            pm2 restart index.js
